### ISSUE TITLE
Create helm chart repository

### ISSUE THREAD

**Issue by Abhi94N** [IllumiDesk/illumidesk#336]
Create a [helm-chart repository using the GitHub pages option](https://helm.sh/docs/topics/chart_repository/).

**Comment by jgwerner** [comment]
Let's rephrase this as "Create a Helm Chart repository in the existing illumidesk/helm-chart GitHub repository with a `gh-pages` branch".

**Comment by jgwerner** [comment]
Closing and recreating in `illumidesk/helm-chart` repo.
