### ISSUE TITLE
Assignment creation not working with the # in assignment name

### ISSUE THREAD

**Issue by jgwerner** [IllumiDesk/illumidesk#421]
Launching IllumiDesk as an external tool with LTI 1.3 where the assignments contain the `#` in the name result in the name not being normalized and the assignment is not created in the grader database.

To reproduce with the Canvas LMS:

- Add a LTI 1.3 application to a course with the Client ID option (LTI 1.3)
- Create a new assignment where the name has the `#` character, for example. `Assignment #1`
- Launch the external tool by clicking ton the assignment link
- In the Grader Console that corresponds to the Canvas LMS course, view the assignments list

**Comment by netoisc** [comment]
Fixed with https://github.com/IllumiDesk/illumidesk.next/pull/1
