### ISSUE TITLE
Stress and Load test helm chart to validate loads

### ISSUE THREAD

**Issue by Abhi94N** [IllumiDesk/illumidesk#613]
1. Create a script to launch multiple single-user notebooks at once from the hub. 
2. Collect data for stress testing
3. Repeat steps 1 and 2 for graders by launching multiple graders from the grader-setup-service 
4. Take a look into [kboom](https://github.com/mhausenblas/kboom) for load testing

**Comment by jgwerner** [comment]
@Abhi94N closing and moving to the illumidesk/infra repo.
